from typing import Optional, Protocol, Sequence

from junip3r.labeller.data.types.abc import Box, ILabellerObject, IInstance, IInstanceType, InstanceID, Point, Selection
from junip3r.labeller.model.image_state import ImageStateChangeFlags


class IUndoModel(Protocol):
    def get_instances(self, image_index: int) -> Sequence[IInstance]: ...
    def get_instance(self, image_index: int, instance_id: InstanceID) -> IInstance | None: ...
    def insert_instance(self, image_index: int, instance: IInstance, insertion_index: int = None) -> None: ...
    def remove_instance(self, image_index: int, instance_id: InstanceID) -> None: ...
    def replace_instance(self, image_index: int, instance_id: InstanceID, instance: IInstance) -> None: ...
    def change_instance_type(self, image_index: int, instance_id: InstanceID, instance_type: IInstanceType) -> None: ...
    def get_selection(self, image_index: int) -> Optional[Selection]: ...
    def set_selection(self, image_index: int, selection: Optional[Selection]) -> None: ...
    def get_new_instance_type(self, image_index: int) -> IInstanceType | None: ...
    def set_new_instance_type(self, image_index: int, instance_type: IInstanceType | None) -> None: ...
    def get_member(self, image_index: int, selection: Selection) -> ILabellerObject: ...
    def set_keypoint(self, image_index: int, selection: Selection, point: Point | None, visibility: float = 2.0) -> None: ...
    def set_bounding_box(self, image_index: int, selection: Selection, box: Box | None) -> None: ...
    def set_polygon(self, image_index: int, selection: Selection, points: Sequence[Point]) -> None: ...
    def set_polygon_point(self, image_index: int, selection: Selection, point_index: int, point: Point) -> None: ...
    def set_polyline(self, image_index: int, selection: Selection, points: Sequence[Point]) -> None: ...
    def set_polyline_point(self, image_index: int, selection: Selection, point_index: int, point: Point) -> None: ...


class IChangeTracker(Protocol):
    def set_flags(self, image_index: int, flags: ImageStateChangeFlags) -> None: ...
