from pathlib import Path
from typing import Optional, Protocol, Sequence

import numpy as np

from junip3r.common.tags.data import Tags
from junip3r.labeller.config.data import InstanceType
from junip3r.labeller.data.types.abc import Box, InstanceID, Point, Selection, InstanceMember
from junip3r.labeller.data.types.data import Instance
from junip3r.labeller.model.image_state import ImageStateChangeFlags


class IReadOnlyAppModel(Protocol):
    """Read-only image/instance access, satisfied by AppModel.

    For consumers (e.g. dataset export) that only need to read data and don't need the
    write/undo surface of IUndoModel.
    """
    def get_num_images(self) -> int: ...
    def get_image(self, image_index: int) -> np.ndarray: ...
    def get_image_name(self, image_index: int) -> str: ...
    def get_image_file(self, image_index: int) -> Optional[Path]: ...
    def get_instance_types(self, image_index: int) -> Sequence[InstanceType]: ...
    def get_instances(self, image_index: int) -> Sequence[Instance]: ...
    def get_tags(self, image_index: int) -> Tags: ...


class IUndoModel(Protocol):
    def get_instances(self, image_index: int) -> Sequence[Instance]: ...
    def get_instance(self, image_index: int, instance_id: InstanceID) -> Instance | None: ...
    def insert_instance(self, image_index: int, instance: Instance, insertion_index: int = None) -> None: ...
    def remove_instance(self, image_index: int, instance_id: InstanceID) -> None: ...
    def replace_instance(self, image_index: int, instance_id: InstanceID, instance: Instance) -> None: ...
    def change_instance_type(self, image_index: int, instance_id: InstanceID, instance_type: InstanceType) -> None: ...
    def get_selection(self, image_index: int) -> Optional[Selection]: ...
    def set_selection(self, image_index: int, selection: Optional[Selection]) -> None: ...
    def get_new_instance_type(self, image_index: int) -> InstanceType | None: ...
    def set_new_instance_type(self, image_index: int, instance_type: InstanceType | None) -> None: ...
    def get_member(self, image_index: int, selection: Selection) -> InstanceMember | None: ...
    def set_keypoint(self, image_index: int, selection: Selection, point: Point | None, visibility: float = 2.0) -> None: ...
    def set_bounding_box(self, image_index: int, selection: Selection, box: Box | None) -> None: ...
    def set_polygon(self, image_index: int, selection: Selection, points: Sequence[Point]) -> None: ...
    def set_polygon_point(self, image_index: int, selection: Selection, point_index: int, point: Point) -> None: ...
    def set_polyline(self, image_index: int, selection: Selection, points: Sequence[Point]) -> None: ...
    def set_polyline_point(self, image_index: int, selection: Selection, point_index: int, point: Point) -> None: ...


class IChangeTracker(Protocol):
    def set_flags(self, image_index: int, flags: ImageStateChangeFlags) -> None: ...
