from pathlib import Path
from typing import Protocol, List, Set, Tuple, Callable


class ISelectionStrategy(Protocol):
    def supports_per_video(self) -> bool: ...
    def supports_total(self) -> bool: ...
    def select(self, video_file: Path, num_frames: int, cancel_callback: Callable[[], bool] = None) -> Set[int]: ...
    def select_total(self, video_files: List[Path], num_frames: int, cancel_callback: Callable[[], bool] = None) -> List[Set[int]]: ...
